appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bFv7SZ5zdtpvx6MS8tKSG9vAbQkWfeiKofC8IiDNvDH6o1glrLEoR7ur8McwUJ0pZ48AWpgygdnVQydK2uFwjWOs1CRGj4IuKkzCzfD7qZ+YIZlhVHTH1IxmA0ceRyl3Yv1i1MrYA57hN6m78WB1YYI7/O32y84C6nJC8zJLJqgxmPcBwRdF8II7IllkVt7dpJEz2z9mMQmOnTKxa7aUpSDmh/gY/JfjdA2X1xJKSu9pm03BDdxg0FJCMyJgNSZmg0/pf1VzlDiQCy+OvE2NHu0ydAxdzZI+9kcLqf1qp1sG32/2JFzwtVi8DvxWJzfijad/h4wo5Cup+cMGy5mlx68FdBEvaqzKOonRa7idrXWY3Stja0jy1v2qcR3YSCMismrn9rAN5OXQ0jYL6rSCc91BhQbiZco+0LovZzgO7RRzlbgIxkMKcrK5fDH9VnIUmByYKXtxesGyDFuP68jZarKhnw1fzIlG0TqtOIrhIfFvdw0CToAyHphGxWiAXA5vxZTOaXkLBl/U2+EuckxUdRru8sKZ6TTIyJlwNdiI9oaQUc7McH4gpaGN6YiBTYBDGCcKvXf1EiJ47uPE9ew0rMed0INphI3IFvz760fe2C1XAz8TiXE90JP9VG2hThnJ1Mfr/aee9k0OjQ8DbsJTdVvmphJKaPtYWdMEbZ0vBzg=}
